#!/bin/bash
# backup-config — Copy the AdGuard config somewhere safe
#
# Generated by `gw apply` from [[job]] in gateway.toml.
# Schedule: 0 4 * * *   User: root
set -euo pipefail
install -d /var/backups/gateway
cp -a /opt/AdGuardHome/AdGuardHome.yaml \
      /var/backups/gateway/AdGuardHome-$(date +%F).yaml
find /var/backups/gateway -name 'AdGuardHome-*.yaml' -mtime +14 -delete
