#!/bin/bash
# speedtest — Log throughput through the tunnel
#
# Generated by `gw apply` from [[job]] in gateway.toml.
# Schedule: @hourly   User: nobody
set -euo pipefail
curl -o /dev/null -s -w 'down %{speed_download} B/s\n' \
     --socks5-hostname 127.0.0.1:10808 \
     https://speed.cloudflare.com/__down?bytes=10000000
