package cli

import (
	"os"
	"path/filepath"
	"testing"
)

// fakeCheckout makes a directory look like the repo.
func fakeCheckout(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "cmd", "gw"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gateway.toml"), []byte("[net]\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestGWRepoOverrideWins(t *testing.T) {
	repo := fakeCheckout(t)
	t.Setenv("GW_REPO", repo)
	t.Setenv("GW_CONFIG", "")

	paths, err := Resolve()
	if err != nil {
		t.Fatal(err)
	}
	if paths.Repo != repo {
		t.Errorf("repo is %q, want %q", paths.Repo, repo)
	}
	if paths.Config != filepath.Join(repo, "gateway.toml") {
		t.Errorf("config is %q", paths.Config)
	}
}

// The privileged helper is a copy of the binary at
// /usr/local/lib/gateway/gw-action, deliberately outside the repo. Walking up
// from it gives /usr/local/lib, and every config read then fails with
// "open /usr/local/lib/gateway.toml: no such file or directory" — a path
// nobody recognises, on a box where the config is plainly present.
func TestInstalledHelperFindsTheRepoFromTheEnvFile(t *testing.T) {
	repo := fakeCheckout(t)
	t.Setenv("GW_REPO", "")
	t.Setenv("GW_CONFIG", "")

	// The env file apply renders, recording where the repo actually is.
	envDir := t.TempDir()
	envFile := filepath.Join(envDir, "env")
	body := "# Generated by `gw apply`\nREPO=\"" + repo + "\"\nWAN_IF=\"eth0\"\n"
	if err := os.WriteFile(envFile, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	old := EnvFile
	EnvFile = envFile
	t.Cleanup(func() { EnvFile = old })

	paths, err := Resolve()
	if err != nil {
		t.Fatal(err)
	}
	// The test binary lives in a temp dir that is not a checkout, so resolution
	// must have fallen through to the env file.
	if paths.Repo != repo {
		t.Errorf("repo resolved to %q, want %q from the env file", paths.Repo, repo)
	}
	if _, err := os.Stat(paths.Config); err != nil {
		t.Errorf("the resolved config does not exist: %v", err)
	}
}

// A REPO that no longer exists must not be believed — an old env file pointing
// at a moved checkout is worse than no answer.
func TestStaleEnvFileIsIgnored(t *testing.T) {
	t.Setenv("GW_REPO", "")
	t.Setenv("GW_CONFIG", "")

	envDir := t.TempDir()
	envFile := filepath.Join(envDir, "env")
	if err := os.WriteFile(envFile, []byte(`REPO="/opt/gone"`+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	old := EnvFile
	EnvFile = envFile
	t.Cleanup(func() { EnvFile = old })

	paths, err := Resolve()
	if err != nil {
		t.Fatal(err)
	}
	if paths.Repo == "/opt/gone" {
		t.Error("a REPO pointing at a directory that is not a checkout was used")
	}
}

// A fresh clone has no gateway.toml — it is gitignored — and `gw init` has to
// work there, so cmd/gw is what identifies a checkout.
func TestFreshCloneWithoutAConfigIsStillACheckout(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "cmd", "gw"), 0o755); err != nil {
		t.Fatal(err)
	}
	if !isCheckout(dir) {
		t.Error("a clone with no gateway.toml was not recognised as a checkout")
	}
}

func TestInstallDirectoriesAreNotCheckouts(t *testing.T) {
	for _, dir := range []string{"/usr/local/lib", "/usr/local", "/", ""} {
		if isCheckout(dir) {
			t.Errorf("%q was mistaken for a checkout", dir)
		}
	}
}

func TestEnvParsesShellQuoting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "env")
	body := `# a comment
REPO="/opt/gateway"
GEO_FILES="geoip geosite"
EMPTY=""
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	env := Env(path)
	if env["REPO"] != "/opt/gateway" {
		t.Errorf("REPO is %q", env["REPO"])
	}
	if env["GEO_FILES"] != "geoip geosite" {
		t.Errorf("a quoted value with a space was mangled: %q", env["GEO_FILES"])
	}
	if _, ok := env["EMPTY"]; !ok {
		t.Error("an empty value was dropped entirely")
	}
	if _, ok := env["# a comment"]; ok {
		t.Error("a comment was parsed as a setting")
	}
}
