package fixtures

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite tests/fixtures from gateway.example.toml")

var repoRoot = func() string {
	dir, err := filepath.Abs("../..")
	if err != nil {
		panic(err)
	}
	return dir
}()

// The committed fixtures must be exactly what the example config generates.
//
// A fixture that has drifted from the example silently stops exercising what it
// was written for, and the golden files are derived from these — so a stale
// fixture quietly invalidates the renderer's entire acceptance test.
func TestFixturesAreGenerated(t *testing.T) {
	example, err := os.ReadFile(filepath.Join(repoRoot, "gateway.example.toml"))
	if err != nil {
		t.Fatal(err)
	}
	built, err := Build(string(example))
	if err != nil {
		t.Fatalf("generating fixtures: %v", err)
	}

	dir := filepath.Join(repoRoot, "tests/fixtures")
	if *update {
		for _, f := range built {
			path := filepath.Join(dir, f.Name+".toml")
			if err := os.WriteFile(path, []byte(f.Body), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		t.Logf("regenerated %d fixtures", len(built))
		return
	}

	generated := map[string]bool{}
	for _, f := range built {
		generated[f.Name] = true
		path := filepath.Join(dir, f.Name+".toml")
		want, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("%s.toml is missing — run: go test ./internal/fixtures -update", f.Name)
			continue
		}
		if string(want) != f.Body {
			t.Errorf("tests/fixtures/%s.toml is stale — run: go test ./internal/fixtures -update\n%s",
				f.Name, firstDifference(string(want), f.Body))
		}
	}

	// A fixture on disk that nothing generates is one nobody maintains.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var orphans []string
	for _, e := range entries {
		// Dot-prefixed files are scratch: other test packages write candidates
		// here so an outbound's relative `file` path still resolves, and Go
		// runs packages in parallel. Go's own tooling ignores them too.
		if e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".toml")
		if strings.HasSuffix(e.Name(), ".toml") && !generated[name] {
			orphans = append(orphans, e.Name())
		}
	}
	sort.Strings(orphans)
	if len(orphans) > 0 {
		t.Errorf("these fixtures are not generated by internal/fixtures, so nothing "+
			"keeps them in step with the example config: %s", strings.Join(orphans, ", "))
	}
}

// Every derived fixture must differ from the example, or it is testing the
// default under another name.
func TestEveryFixtureDiffersFromTheExample(t *testing.T) {
	example, err := os.ReadFile(filepath.Join(repoRoot, "gateway.example.toml"))
	if err != nil {
		t.Fatal(err)
	}
	built, err := Build(string(example))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range built {
		if f.Name == "default" {
			continue // it is the example, deliberately
		}
		if f.Body == string(example) {
			t.Errorf("fixture %s is identical to the example", f.Name)
		}
	}
}

// A missing anchor must be an error, not a silent no-op that leaves the default
// in place.
func TestMissingAnchorIsAnError(t *testing.T) {
	if _, err := Build("[net]\nwan_if = \"eth0\"\n"); err == nil {
		t.Fatal("generating from a config with none of the anchors reported success")
	}
}

func firstDifference(want, got string) string {
	wl, gl := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(wl) || i < len(gl); i++ {
		var w, g string
		if i < len(wl) {
			w = wl[i]
		}
		if i < len(gl) {
			g = gl[i]
		}
		if w != g {
			return "  first difference at line " + itoa(i+1) + ":\n    committed: " + w +
				"\n    generated: " + g
		}
	}
	return ""
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}
