#!/usr/bin/env bash
# Reclaim disk in the gateway checkout, without breaking it.
#
#   scripts/cleanup.sh              list what would go, then ask
#   scripts/cleanup.sh --dry-run    list what would go, change nothing
#   scripts/cleanup.sh --yes        no prompt, for a cron job
#   scripts/cleanup.sh --gc         also repack .git (slow on a thin client)
#   scripts/cleanup.sh --go-cache   also drop Go's build and module caches
#
# The deployment IS a git checkout — that is how a fix reaches the box, and
# `gw status` compares the running binary against it. So the rule this script
# is built around is:
#
#   NOTHING GIT TRACKS IS EVER DELETED.
#
# Deleting a tracked file to save a few hundred kilobytes leaves the worktree
# dirty, and the next `git pull` either refuses to run or quietly puts the file
# back — so the space returns and the box is now in a state nobody expects.
# Every target below is checked against the index before it is touched, and one
# that turns out to be tracked is skipped with a line saying so.
#
# That rules out tests/, docs/, dashboard/src and the Go sources. They are all
# dead weight at runtime and they come to about 3 MB, against the 130-odd MB
# this does remove. Not a trade worth a checkout that cannot take an update.
#
# Left alone on purpose, and each for its own reason:
#
#   vendor/      the box compiles with -mod=vendor and no network. Without it
#                the next `git pull` cannot be built.
#   build/       regenerated by every `gw render`, and about 300 KB. Removing
#                it frees nothing and makes the next `gw diff` re-render first.
#   bin/gw       the running binary. /usr/local/bin/gw is a symlink to it.
#   gateway.toml, outbounds/*.json    the config, and the credentials.
_self="$0"
while [ -L "$_self" ]; do
  _link="$(readlink "$_self")"
  case "$_link" in /*) _self="$_link" ;; *) _self="$(dirname "$_self")/$_link" ;; esac
done
source "$(dirname "$_self")/../lib/common.sh"

DRY=0
GC=0
GOCACHE_TOO=0
for arg in "$@"; do
  case "$arg" in
    --dry-run|-n) DRY=1 ;;
    --yes|-y)     GW_YES=1 ;;
    --gc)         GC=1 ;;
    --go-cache)   GOCACHE_TOO=1 ;;
    -h|--help)    sed -n '2,7p' "$_self"; exit 0 ;;
    *)            die "unknown argument: $arg (try --help)" ;;
  esac
done

cd "$REPO" || die "cannot enter $REPO"

# ---------------------------------------------------------------- helpers --

# tracked <path> — true when git has this path in the index.
#
# `git ls-files` on a directory lists what it holds, so a directory containing
# any tracked file counts as tracked. That is the answer we want: removing such
# a directory is precisely the mistake this guard exists to prevent.
tracked() {
  git rev-parse --git-dir >/dev/null 2>&1 || return 1
  [ -n "$(git ls-files -- "$1" 2>/dev/null | head -1)" ]
}

size_of() { du -sh "$1" 2>/dev/null | cut -f1; }
kb_of()   { du -sk "$1" 2>/dev/null | cut -f1; }

# The plan, filled in below and printed before anything is removed. Parallel
# arrays rather than one string per entry, so a path with a space in it — the
# Go cache under a home directory that has one — survives.
PLAN_PATH=()
PLAN_WHY=()
PLAN_KB=0

# consider <path> <why> — add a target to the plan, unless git tracks it.
consider() {
  local path="$1" why="$2"
  [ -e "$path" ] || return 0
  if tracked "$path"; then
    warn "keeping $path — git tracks it; removing it would leave the checkout dirty"
    return 0
  fi
  PLAN_PATH+=("$path")
  PLAN_WHY+=("$why")
  PLAN_KB=$(( PLAN_KB + $(kb_of "$path") ))
}

# ------------------------------------------------------------------ plan --

info "gateway checkout: $REPO ($(size_of "$REPO"))"

# 130+ MB, and the whole reason this script exists. The dashboard is built on a
# workstation and dashboard/dist is committed; the box has no Node and never
# runs vite, so this is the input to a build that cannot happen here. dist/
# itself is tracked and stays — it is embedded into bin/gw at compile time.
consider dashboard/node_modules "the box has no Node; dashboard/dist is committed and embedded"

# Editor and merge leftovers. .gitignore already lists these, so they are
# untracked by construction — consider() re-checks rather than trusting that.
# node_modules and vendor are pruned from the walk: both are large, and one of
# them is already on the list.
while IFS= read -r -d '' f; do
  consider "$f" "editor or merge leftover"
done < <(find . \( -name .git -o -name node_modules -o -name vendor \) -prune -o \
              \( -name '*.bak' -o -name '*.orig' -o -name '*.rej' \
                 -o -name '*~' -o -name '.DS_Store' \) -print0 2>/dev/null)

# Go's caches: not inside the checkout, but created by building it here, and
# routinely larger than everything else combined. Both are safe to lose — the
# build cache only makes the next rebuild slower, and the module cache is never
# consulted at all because the box compiles -mod=vendor.
#
# Opt-in all the same, and this is the reason: those directories are per-USER
# and shared with every other Go project that account has ever built. On the
# box that set is empty and dropping them is free. Run this on the workstation
# you develop from, where it is not empty, and the default would quietly delete
# gigabytes belonging to unrelated work. A flag makes it a decision.
gocache_dirs() {
  local var dir
  for var in GOCACHE GOMODCACHE; do
    dir=$(go env "$var" 2>/dev/null || true)
    [ -n "$dir" ] && [ -d "$dir" ] || continue
    case "$dir" in
      "$REPO"|"$REPO"/*) continue ;;        # never a path inside the checkout
      /|/usr|/etc|/var|/home|/root) continue ;;  # never something that broad
    esac
    printf '%s\n' "$dir"
  done
}

if [ "$GOCACHE_TOO" = "1" ]; then
  while IFS= read -r dir; do
    [ -n "$dir" ] || continue
    consider "$dir" "rebuilt on demand; the box compiles with -mod=vendor"
  done < <(gocache_dirs)
fi

# --------------------------------------------------------------- report --

if [ "${#PLAN_PATH[@]}" -eq 0 ]; then
  info "nothing to remove — this checkout is already lean"
else
  echo
  info "to remove (about $(( PLAN_KB / 1024 )) MB):"
  for i in "${!PLAN_PATH[@]}"; do
    printf '    %-8s %s\n' "$(size_of "${PLAN_PATH[$i]}")" "${PLAN_PATH[$i]}"
    printf '             %s\n' "${PLAN_WHY[$i]}"
  done
fi

if [ "$GC" = "1" ]; then
  echo
  info "and repacking .git (currently $(size_of .git))"
fi

# Named rather than removed, so the space is visible without being taken. On
# the box this is usually the second biggest win after node_modules.
if [ "$GOCACHE_TOO" = "0" ]; then
  while IFS= read -r dir; do
    [ -n "$dir" ] || continue
    warn "not touching $dir ($(size_of "$dir")) — shared with every Go build by this user; pass --go-cache to include it"
  done < <(gocache_dirs)
fi

if [ "$DRY" = "1" ]; then
  echo
  info "dry run — nothing was removed"
  exit 0
fi

if [ "${#PLAN_PATH[@]}" -eq 0 ] && [ "$GC" = "0" ]; then
  exit 0
fi

# -------------------------------------------------------------- execute --

echo
confirm "proceed?"

for i in "${!PLAN_PATH[@]}"; do
  rm -rf -- "${PLAN_PATH[$i]}" \
    || warn "could not remove ${PLAN_PATH[$i]} — check permissions"
done
[ "${#PLAN_PATH[@]}" -gt 0 ] && info "removed ${#PLAN_PATH[@]} item(s)"

if [ "$GC" = "1" ]; then
  info "repacking .git — this is the slow part"
  # --prune=now rather than --aggressive: aggressive rewrites every delta and
  # can run for many minutes on a thin client, for a fraction more space.
  git gc --prune=now --quiet 2>/dev/null \
    || warn "git gc failed — the checkout is fine, just not repacked"
  info ".git is now $(size_of .git)"
fi

info "checkout is now $(size_of "$REPO")"
info "nothing tracked was touched: 'git status --short' should be as it was"
