package render

import (
	"fmt"
	"strings"

	"github.com/am1nr/gateway/internal/config"
)

// Jobs renders scheduled jobs as a cron table plus one script per job.
//
// The script bodies live in their own files rather than inline in the crontab
// because cron treats % as a newline and gives no error for a malformed line —
// it just never runs. A one-line "run this script" entry keeps the crontab
// trivially correct and leaves the bash where it can be read and tested.
func Jobs(c *config.Config) (map[string]string, error) {
	files := map[string]string{}
	lines := []string{
		"# Generated by `gw apply` — DO NOT EDIT ON THE BOX.",
		"# Edit [[job]] entries in gateway.toml, or use `gw job` / the dashboard.",
		"SHELL=/bin/bash",
		"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
		"",
	}

	for _, job := range c.Jobs {
		path := "usr/local/lib/gateway/jobs/" + job.Name + ".sh"
		title := "# " + job.Name
		if job.Description != "" {
			title += " — " + job.Description
		}
		header := []string{
			"#!/bin/bash",
			title,
			"#",
			"# Generated by `gw apply` from [[job]] in gateway.toml.",
			fmt.Sprintf("# Schedule: %s   User: %s", job.Schedule, job.User),
			"set -euo pipefail",
			"",
		}
		files[path] = strings.Join(header, "\n") +
			strings.TrimRight(job.Script, "\n") + "\n"

		if !job.Enabled {
			lines = append(lines, "# disabled: "+job.Name)
			continue
		}
		if job.Description != "" {
			lines = append(lines, "# "+job.Description)
		}
		// Output is captured by cron and mailed nowhere on a box with no MTA,
		// so send it to the journal where `gw logs` can find it.
		lines = append(lines, fmt.Sprintf(
			"%s\t%s\t/usr/local/lib/gateway/jobs/%s.sh 2>&1 | logger -t gw-job-%s",
			job.Schedule, job.User, job.Name, job.Name))
	}

	lines = append(lines, "")
	crontab := strings.Join(lines, "\n")

	// cron reads % in a crontab line as a newline and silently truncates
	// there, so a job whose schedule, user or name smuggled one in would
	// become a different command with no error anywhere. Nothing upstream can
	// produce this today; it is asserted because the consequence is invisible.
	for _, line := range strings.Split(crontab, "\n") {
		if strings.HasPrefix(line, "#") || line == "" {
			continue
		}
		if strings.Contains(line, "%") {
			return nil, fmt.Errorf(
				"crontab line contains '%%', which cron treats as a newline: %s", line)
		}
	}

	files["etc/cron.d/gw-jobs"] = crontab
	return files, nil
}
