package config

import (
	"net/netip"

	"github.com/am1nr/gateway/internal/jsonx"
)

// TailnetV4 is the CGNAT range Tailscale assigns from. It is never routed into
// the tunnel and never treated as a poisoned DNS answer.
const TailnetV4 = "100.64.0.0/10"

// BuiltinPolicies are the three policies every config has, before profiles.
var BuiltinPolicies = []string{"proxy", "direct", "block"}

// ReservedDst are destinations that must never enter the tunnel: local scopes,
// the tailnet, and anything the kernel treats specially.
var ReservedDst = []string{
	"0.0.0.0/8",
	"10.0.0.0/8",
	"127.0.0.0/8",
	"169.254.0.0/16",
	"172.16.0.0/12",
	"192.168.0.0/16",
	"224.0.0.0/4",
	"240.0.0.0/4", // includes 255.255.255.255
	TailnetV4,
}

// GeoSource is one place routing data comes from.
//
// Two shapes, as before: a GitHub repo whose latest release is scanned for
// every .dat asset — so a new rule file appearing upstream arrives on its own —
// or an explicit list of names fetched through a URL template.
type GeoSource struct {
	// Name labels the source in logs and in the dashboard. Defaults to the repo
	// or the template's host.
	Name string
	// Repo is owner/name. Release discovery is used when Files is empty.
	Repo string
	// URLTemplate has {0} replaced by each file name.
	URLTemplate string
	// Files pins the set. Empty means "whatever the release ships", which
	// requires Repo.
	Files []string
	// Enabled allows a source to be kept in the config but skipped.
	Enabled bool
}

// Client is a per-address policy override.
type Client struct {
	IP     string
	Name   string
	Policy string
}

// Upstream is an extra Xray server that profiles can route selected traffic
// through (a work VPN, a second exit country, ...).
type Upstream struct {
	Name     string
	Outbound *Outbound
}

// ProfileRoute is one destination-specific exception inside a profile.
type ProfileRoute struct {
	Via     string // the name written in the config: an upstream, or proxy/direct/block
	Tag     string // the Xray outbound tag Via resolves to
	Domains []string
	IPs     []string
}

// Profile is a built-in policy plus destination-specific exceptions: "behave
// like Base, except send these domains/networks via X".
type Profile struct {
	Name   string
	Base   string
	Routes []ProfileRoute
}

// CustomRoute is a raw Xray routing rule spliced into the generated pipeline.
// The TOML table maps one-to-one onto Xray's rule JSON, so the table is the
// rule; Position is the only key the gateway consumes.
type CustomRoute struct {
	Position string // "first", "before" (default) or "after"
	// Rule is the Xray routing rule, with keys in the order they were written.
	// Order carries no meaning to Xray, but the dashboard round-trips these
	// rules through an editor and reordering someone's keys on every save is
	// its own small betrayal.
	Rule *jsonx.Object
}

// Job is a bash script on a cron schedule, rendered into /etc/cron.d.
type Job struct {
	Name        string
	Schedule    string
	Script      string
	User        string
	Enabled     bool
	Description string
}

// Config is a validated gateway.toml plus everything derived from it.
type Config struct {
	Raw  map[string]any
	Path string

	// ---- net ----
	WANIf     string
	LAN       netip.Prefix
	LANCidr   string
	Router    string
	BoxIP     string
	PrefixLen int
	IPv6Mode  string

	// ---- xray ----
	TproxyPort     int
	SocksPort      int
	HTTPPort       int
	APIPort        int
	LogLevel       string
	DomainStrategy string
	OutboundMark   int

	// ---- performance ----
	BufferSizeKB  int
	TCPCongestion string
	TCPNoDelay    bool
	ConnIdle      int

	Server   *Outbound
	Fallback *Outbound

	// ---- routing ----
	DirectGeosite   []string
	DirectGeoIP     []string
	BlockGeosite    []string
	BlockBittorrent bool
	ExtraLocal      []string
	DropPrivate     bool

	// ---- geodata ----
	// GeoSources are the places routing data is fetched from, in order. When
	// two provide a file of the same name the FIRST wins, matching how
	// everything else here resolves — routing rules, policy precedence — and
	// the updater reports which source each file came from.
	GeoSources  []GeoSource
	GeoMinBytes int

	BootstrapProxy string

	// ---- dns ----
	DNSPort        int
	UIPort         int
	UpProxied      []string
	UpDirect       []string
	DirectSuffixes []string
	Bootstrap      []string
	DNSIntercept   bool
	Blocklists     []string
	QuerylogDays   int
	StatslogDays   int
	// UIEnabled reports whether AdGuard's admin interface is reachable over the
	// network at all.
	UIEnabled bool
	// UIAllow are the networks that may reach it. Empty means none.
	UIAllow []string

	// Ordered, because both the outbound list and the routing rules are
	// generated by iterating them and order is behaviour in Xray.
	Upstreams []*Upstream
	Profiles  []*Profile

	// RouteTargets maps a name a profile rule may use to its Xray outbound tag.
	RouteTargets map[string]string

	Routes []CustomRoute

	Policies      []string
	Intercepted   map[string]bool
	DefaultPolicy string
	Clients       []Client

	// ---- tailscale ----
	TSEnabled      bool
	TSSSH          bool
	TSExitNode     bool
	TSSubnetRouter bool
	TSExitPolicy   string
	TSRouteControl bool
	TSLifelineMin  int

	// ---- web ----
	WebEnabled      bool
	WebListen       string
	WebPort         int
	WebTLS          bool
	WebCert         string
	WebKey          string
	WebAllow        []string
	SessionHours    int
	MaxFailedLogins int
	LockoutMinutes  int

	Jobs []Job

	// ---- health ----
	HealthInterval   int
	ProbeURL         string
	ProbeTimeout     int
	DomesticProbeURL string
	RestartAfter     int
	FallbackAfter    int

	// ---- system ----
	Timezone           string
	JournalMax         string
	Zram               bool
	BBR                bool
	Unattended         bool
	AutoUpdate         string
	AutoUpdateSchedule string
	SSHAllowLAN        bool
	SSHAllowTailnet    bool

	upstreamByName map[string]*Upstream
	profileByName  map[string]*Profile

	// routeKeyOrder records the key order of each [[route]] table as written,
	// recovered from the TOML decoder's metadata. nil when the config was not
	// read from a file, in which case keys are sorted for determinism.
	routeKeyOrder [][]string
}

// Upstream returns the named upstream, if it exists.
func (c *Config) Upstream(name string) (*Upstream, bool) {
	u, ok := c.upstreamByName[name]
	return u, ok
}

// Profile returns the named profile, if it exists.
func (c *Config) Profile(name string) (*Profile, bool) {
	p, ok := c.profileByName[name]
	return p, ok
}
